/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * 
 * This file is automatically updated when contracts are deployed.
 * It contains the latest factory addresses and V2 chain detection.
 * 
 * Generated by: contracts/script/Deploy.s.sol
 * Last updated: 1770876020
 * Chain ID: 42161
 */

export interface DeploymentInfo {
  chainId: number
  factoryAddress: string
  blockNumber?: number
  timestamp?: number
  isV2: boolean
  deploymentHash?: string
}

// Auto-generated deployment registry
export const DEPLOYMENTS: Record<number, DeploymentInfo> = {
  // Auto-generated deployment (latest)
  42161: {
    chainId: 42161,
    factoryAddress: "0xfe367D31d181D305dcF5AAaa345a70A65c345153",
    isV2: true,
    blockNumber: 24438765,
    timestamp: 1770876020
  },

  // Legacy V1 deployments (manually maintained)
  42220: {
    chainId: 42220,
    factoryAddress: "0x86dBf7076202FDf89792038B97e41aC8A4A8Bef9",
    isV2: false
  },
  44787: {
    chainId: 44787,
    factoryAddress: "0x86dBf7076202FDf89792038B97e41aC8A4A8Bef9",
    isV2: false
  }
}

// Auto-generated V2 chain list
export const V2_CHAINS = Object.entries(DEPLOYMENTS)
  .filter(([_, info]) => info.isV2)
  .map(([chainId, _]) => parseInt(chainId))

// Auto-generated factory addresses
export const FACTORY_ADDRESSES = Object.fromEntries(
  Object.entries(DEPLOYMENTS).map(([chainId, info]) => [
    chainId,
    info.factoryAddress
  ])
) as Record<number, string>

// Helper functions
export function isV2Chain(chainId: number): boolean {
  return DEPLOYMENTS[chainId]?.isV2 || false
}

export function getFactoryAddress(chainId: number): string | undefined {
  return DEPLOYMENTS[chainId]?.factoryAddress
}

export function getDeploymentInfo(chainId: number): DeploymentInfo | undefined {
  return DEPLOYMENTS[chainId]
}

// Generation metadata
export const GENERATED_AT = "1770876020"
export const GENERATOR = "Cookie Jar Deployment System v2.0"
export const DEPLOYED_CHAIN = 42161
