[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 1000
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

# Lightweight profile for quick compilation (no CREATE2)
[profile.lite]
via_ir = false
optimizer = false
optimizer_runs = 1
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
PRIVATE_KEY = "${PRIVATE_KEY}"
RPC_URL = "${RPC_URL}"
# Allow writing deployment files for local development
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "." },
    { access = "read-write", path = "local-deployment.json" }
]

[rpc_endpoints]
sepolia = "${SEPOLIA_URL}"
celo-alfajores = "${ALFAJORES_URL}"
celo = "${CELO_URL}"

[etherscan]
celo = { key = "blockscout", url = "https://celo.blockscout.com/api" }
celo-alfajores = { key = "blockscout", url = "https://celo-alfajores.blockscout.com/api" }
sepolia = { key = "${SEPOLIA_ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
